version: "3.7"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"
  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://zookeeper:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"
  consumer_nodejs:
    build: consumer_nodejs
    container_name: dev-consumer_nodejs
    networks:
      - kafka
    env_file:
      - consumer_nodejs/docker/.env
  producer_python:
    build: producer_python
    container_name: dev-producer_python
    networks:
      - kafka
    env_file:
      - producer_python/docker/.env

networks:
  kafka:
